version: 2.1

orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.8.2

jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          echo "Installing dependencies..."
          npm install 
  
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm test

  publish:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: sughrahassan/tamkeen-software
          tag: v1.0.2
      - docker/push:
          image: sughrahassan/tamkeen-software
          tag: v1.0.2

workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish:
          requires:
            - test
